services:
  - type: web
    name: audio-merger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/audio_merger.py
    buildFilter:
      paths:
        - "**/*.py"
        - "**/requirements.txt"
        - "**/render.yaml"
