services:
  - type: web
    name: audio-merger
    env: python
    plan: free

    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: python audio_merger.py

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
